version: '3.9'

services:
  odoo:
    container_name: ${ODOO_CONTAINER_NAME:-odoo-dev-app-17}
    image: ${ODOO_IMAGE:-odoo}:${ODOO_VERSION:-17.0}
    restart: ${ODOO_RESTART_POLICY:-unless-stopped}
    environment:
      - HOST=postgres
      - USER=${POSTGRES_USER:-odoo}
      - PASSWORD=${POSTGRES_PASSWORD:-odoo}
      - DB_NAME=${POSTGRES_DB:-postgres}
      - INSTALL_MODULES=${ODOO_INSTALL_MODULES:-base}
      - ODOO_INIT_DB=${ODOO_INIT_DB:-True}
    command: ${ODOO_COMMAND:---init=${ODOO_INSTALL_MODULES:-base} --database=${POSTGRES_DB:-postgres}}
    ports:
      - "${ODOO_PORT:-8069}:8069"
    volumes:
      - odoo_data:/var/lib/odoo
      - ${ODOO_ADDONS_PATH:-./addons}:/mnt/extra-addons
    networks:
      - default
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8069/web/health"]
      interval: ${ODOO_HEALTHCHECK_INTERVAL:-30s}
      timeout: ${ODOO_HEALTHCHECK_TIMEOUT:-10s}
      retries: ${ODOO_HEALTHCHECK_RETRIES:-3}
      start_period: ${ODOO_HEALTHCHECK_START_PERIOD:-60s}

  postgres:
    container_name: ${POSTGRES_CONTAINER_NAME:-odoo-dev-postgres-15}
    image: ${POSTGRES_IMAGE:-postgres}:${POSTGRES_VERSION:-15}
    restart: ${POSTGRES_RESTART_POLICY:-unless-stopped}
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-odoo}
      - POSTGRES_USER=${POSTGRES_USER:-odoo}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
    networks:
      - default
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-odoo}"]
      interval: ${POSTGRES_HEALTHCHECK_INTERVAL:-10s}
      timeout: ${POSTGRES_HEALTHCHECK_TIMEOUT:-5s}
      retries: ${POSTGRES_HEALTHCHECK_RETRIES:-5}

networks:
  default:
    name: odoo_network
    driver: bridge

volumes:
  odoo_data:
    name: odoo_data
    driver: local
  postgres_data:
    name: postgres_data
    driver: local